services:
  postgres:
    container_name: postgres
    image: postgres:16.3-alpine
    environment:
      - 'POSTGRES_DB=postgres'
      - 'POSTGRES_USER=root'
      - 'POSTGRES_PASSWORD=root'
    ports:
      - '5432:5432'
